/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicios.ficheros;

import org.junit.jupiter.api.Test;

class AppTest {
    
    @Test 
    void appHasAGreeting() {
        new EjerciciosFicherosApplication();
    }
}
