/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicios.ficheros;

import ejercicios.ficheros.utils.EjerciciosInterface;
import ejercicios.ficheros.examples.Ejercicio1;
import ejercicios.ficheros.examples.Ejercicio2;
import ejercicios.ficheros.examples.Ejercicio3;

public class EjerciciosFicherosApplication {

    public static void main(String[] args) {
        initExcersise(new Ejercicio1());
        initExcersise(new Ejercicio2());
        initExcersise(new Ejercicio3());
    }

    public static void initExcersise(EjerciciosInterface excersise) {
        System.out.println("Nombre del ejercicio: " + excersise.getNameExample());
        System.out.println("Descripcion de Ejercicio: " + excersise.getDescription() + "\n");
        excersise.example();
        System.out.println();
    }
}